package tunnel

import (
	"crypto/rand"
	"fmt"

	"github.com/flynn/noise"
	"golang.org/x/crypto/curve25519"
)

// suite is the Noise cipher suite used by the tunnel:
// Noise_IK_25519_ChaChaPoly_BLAKE2s.
var suite = noise.NewCipherSuite(noise.DH25519, noise.CipherChaChaPoly, noise.HashBLAKE2s)

// newKeypair generates a fresh X25519 keypair using the same primitives as the
// handshake.
func newKeypair() (noise.DHKey, error) {
	return suite.GenerateKeypair(rand.Reader)
}

// publicFromPrivate derives the X25519 public key. This mirrors exactly what
// GenerateKeypair computes, so keys generated by `sr genkey` round-trip.
func publicFromPrivate(priv []byte) ([]byte, error) {
	if len(priv) != 32 {
		return nil, fmt.Errorf("private key must be 32 bytes, got %d", len(priv))
	}
	return curve25519.X25519(priv, curve25519.Basepoint)
}

// newInitiator builds the client-side (initiating) handshake state. The
// initiator must know the responder's static public key in advance (that is
// what makes this pattern IK).
func newInitiator(priv, pub, peerStatic []byte) (*noise.HandshakeState, error) {
	if len(peerStatic) != 32 {
		return nil, fmt.Errorf("peer static key must be 32 bytes, got %d", len(peerStatic))
	}
	return noise.NewHandshakeState(noise.Config{
		CipherSuite:   suite,
		Pattern:       noise.HandshakeIK,
		Initiator:     true,
		Prologue:      []byte(prologue),
		StaticKeypair: noise.DHKey{Private: priv, Public: pub},
		PeerStatic:    peerStatic,
	})
}

// newResponder builds the gateway-side handshake state. The initiator's static
// key is NOT provided up front: it is transmitted (and authenticated) in the
// first handshake message and becomes readable via PeerStatic() once
// ReadMessage succeeds — that is when the gateway checks its allowlist.
func newResponder(priv, pub []byte) (*noise.HandshakeState, error) {
	return noise.NewHandshakeState(noise.Config{
		CipherSuite:   suite,
		Pattern:       noise.HandshakeIK,
		Initiator:     false,
		Prologue:      []byte(prologue),
		StaticKeypair: noise.DHKey{Private: priv, Public: pub},
	})
}
