// Package serverapp exposes the hub's control API: live status of every agent
// and client, relay counters and the operator commands (kick, refresh) that
// the web control plane drives.
//
// The data plane lives in internal/tunnel; this package is a thin, read-mostly
// HTTP façade over one Engine. Authentication is a bearer token shared with
// the web container (generated by the deployment scripts); the API is meant to
// be reachable only from the compose network.
package serverapp

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"errors"
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"

	"selfremote/internal/tunnel"
)

// Config configures the control API.
type Config struct {
	Listen  string // e.g. "0.0.0.0:8770"; empty disables the API
	Token   string // bearer token; empty means "no authentication" (tests only)
	Engine  *tunnel.Engine
	Version string
}

// Server serves the control API.
type Server struct {
	cfg Config
}

// New builds the API server.
func New(cfg Config) *Server { return &Server{cfg: cfg} }

// Totals summarises the peer set.
type Totals struct {
	AgentsTotal   int `json:"agents_total"`
	AgentsOnline  int `json:"agents_online"`
	ClientsTotal  int `json:"clients_total"`
	ClientsOnline int `json:"clients_online"`
}

// Status is the /api/v1/status payload.
type Status struct {
	Version    string             `json:"version"`
	Hostname   string             `json:"hostname"`
	Listen     string             `json:"listen"`
	TunnelCIDR string             `json:"tunnel_cidr"`
	Totals     Totals             `json:"totals"`
	Peers      []tunnel.PeerStats `json:"peers"`
	Relay      tunnel.RelayStats  `json:"relay"`
	Conflicts  []string           `json:"conflicts,omitempty"`
	UpdatedAt  string             `json:"updated_at"`
}

// Snapshot collects the current state.
func (s *Server) Snapshot() Status {
	peers := s.cfg.Engine.Stats()
	st := Status{
		Version:    s.cfg.Version,
		Listen:     s.cfg.Engine.LocalAddr(),
		TunnelCIDR: s.cfg.Engine.TunnelCIDR(),
		Peers:      peers,
		Relay:      s.cfg.Engine.RelayStats(),
		Conflicts:  s.cfg.Engine.Conflicts(),
		UpdatedAt:  time.Now().Format(time.RFC3339),
	}
	st.Hostname, _ = os.Hostname()
	for _, p := range peers {
		switch p.Role {
		case "agent":
			st.Totals.AgentsTotal++
			if p.Connected && p.Authed {
				st.Totals.AgentsOnline++
			}
		default:
			st.Totals.ClientsTotal++
			if p.Connected && p.Authed {
				st.Totals.ClientsOnline++
			}
		}
	}
	sort.Strings(st.Conflicts)
	return st
}

// Handler builds the HTTP routes.
func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "ok")
	})
	mux.HandleFunc("GET /api/v1/status", s.authed(func(w http.ResponseWriter, r *http.Request) {
		writeJSON(w, http.StatusOK, s.Snapshot())
	}))
	mux.HandleFunc("GET /api/v1/agents", s.authed(func(w http.ResponseWriter, r *http.Request) {
		st := s.Snapshot()
		agents := make([]tunnel.PeerStats, 0, len(st.Peers))
		for _, p := range st.Peers {
			if p.Role == "agent" {
				agents = append(agents, p)
			}
		}
		writeJSON(w, http.StatusOK, map[string]any{"agents": agents, "conflicts": st.Conflicts})
	}))
	mux.HandleFunc("POST /api/v1/agents/{id}/kick", s.authed(func(w http.ResponseWriter, r *http.Request) {
		id := r.PathValue("id")
		if !s.cfg.Engine.KickAgent(id) {
			writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "agent 不存在"})
			return
		}
		log.Printf("api: agent %s kicked", id)
		writeJSON(w, http.StatusOK, map[string]any{"ok": true})
	}))
	mux.HandleFunc("POST /api/v1/agents/{id}/refresh", s.authed(func(w http.ResponseWriter, r *http.Request) {
		id := r.PathValue("id")
		if !s.cfg.Engine.RefreshAgent(id) {
			writeJSON(w, http.StatusNotFound, map[string]any{"ok": false, "error": "agent 不存在"})
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"ok": true})
	}))
	return logRequests(mux)
}

// Run serves until ctx is cancelled.
func (s *Server) Run(ctx context.Context) error {
	if s.cfg.Listen == "" {
		<-ctx.Done()
		return nil
	}
	ln, err := net.Listen("tcp", s.cfg.Listen)
	if err != nil {
		return fmt.Errorf("control api listen %s: %w", s.cfg.Listen, err)
	}
	srv := &http.Server{
		Handler:           s.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
	}
	done := make(chan struct{})
	go func() {
		defer close(done)
		if err := srv.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Printf("control api: %v", err)
		}
	}()
	log.Printf("control api: listening on %s", ln.Addr())
	select {
	case <-ctx.Done():
	case <-done:
	}
	shutCtx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	_ = srv.Shutdown(shutCtx)
	return nil
}

// authed requires the shared bearer token when one is configured.
func (s *Server) authed(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if s.cfg.Token != "" {
			h := strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer ")
			if subtle.ConstantTimeCompare([]byte(h), []byte(s.cfg.Token)) != 1 {
				writeJSON(w, http.StatusUnauthorized, map[string]any{"ok": false, "error": "unauthorized"})
				return
			}
		}
		next(w, r)
	}
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(v)
}

func logRequests(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		next.ServeHTTP(w, r)
		if !strings.HasPrefix(r.URL.Path, "/healthz") {
			log.Printf("%s %s (%v)", r.Method, r.URL.Path, time.Since(start).Round(time.Millisecond))
		}
	})
}
